Repository laminas/laminas-migration, pull requests merged in 2019-11, with the labels that each got.

#6 fix: return early when no deps are installed
  src/Command/NestedDepsCommand.php
Labels: bug

#8 fix: rename zend-expressive. file
  config/replacements.php
Labels: bug

#11 Feature: support symfony/console 2.1 - 5
  composer.json
  composer.lock
Labels: enhancement

#14 Fix composer install command
  README.md
Labels: bug, documentation
